version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:

    commands:
      # install yarn
      - apt-get update && apt-get install yarn
      - yarn --version
      # install packages
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  files:
    - ./dist/**/*
    - ./frontend-deploy-buildspec.yml
